services:
  - type: web
    name: tuhi-car-rental
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx wrangler pages dev dist --port $PORT
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22.0.0
      - key: OPENROUTESERVICE_API_KEY
        sync: false
      - key: VITE_OPENROUTESERVICE_API_KEY
        sync: false
      - key: VITE_ADMIN_USERNAME
        sync: false
      - key: VITE_ADMIN_PASSWORD
        sync: false
      - key: VITE_RAZORPAY_KEY_ID
        sync: false
